### ISSUE TITLE
Create Manual Test Documentation

### ISSUE THREAD

**Issue by dbalazs97** [BME-MIT-IET/feelsgoodman-iet-2019#21]

**Comment by klevente** [comment]
Documentation for the manual tests has been created and uploaded to the relevant wiki page:
https://github.com/BME-MIT-IET/feelsgoodman-iet-2019/wiki/Manu%C3%A1lis-tesztek-megtervez%C3%A9se,-v%C3%A9grehajt%C3%A1sa

**Comment by khaled988690** [comment]
Wiki page lgtm.
