### ISSUE TITLE
Add READEME.md

### ISSUE THREAD

**Issue by dbalazs97** [BME-MIT-IET/feelsgoodman-iet-2019#22]

**Comment by klevente** [comment]
Here are the related commits:

https://github.com/BME-MIT-IET/feelsgoodman-iet-2019/commit/60d3bbdca789ea1a6b9828e05bfe6739356e4266
https://github.com/BME-MIT-IET/feelsgoodman-iet-2019/commit/0451894a5bc2cf055fc72663a6158e8010c81984
