### ISSUE TITLE
Create Manual Tests

### ISSUE THREAD

**Issue by dbalazs97** [BME-MIT-IET/feelsgoodman-iet-2019#4]

**Comment by klevente** [comment]
Manual tests were created and the result can be viewed on the wiki page: 
https://github.com/BME-MIT-IET/feelsgoodman-iet-2019/wiki/Manu%C3%A1lis-tesztek-megtervez%C3%A9se,-v%C3%A9grehajt%C3%A1sa

**Comment by theimpulseadmin** [comment]
wiki page lgtm

**Comment by khaled988690** [comment]
Wiki page lgtm.
